import React from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { ConstructionBudget } from '@features/projects/budget/ui/ConstructionBudget';
import { budgetApi } from '@features/projects/budget/api/budgetApi';
import type { BudgetRevision } from '@features/projects/budget/model/types';

vi.mock('@features/projects/budget/api/budgetApi', () => ({ budgetApi: { index: vi.fn(), sources: vi.fn(), revision: vi.fn() } }));
const revision = { id: 'r', title: 'Rozpočet', version: 1, status: 'draft', allocations: [], document: { schemaVersion: 1, figures: {}, nodes: [], sheets: [], issues: [] } } as unknown as BudgetRevision;
beforeEach(() => {
  localStorage.clear();
  vi.mocked(budgetApi.index).mockResolvedValue({ revisions: [revision], permissions: { prices: true, edit: false, confirm: false, allocate: false } });
  vi.mocked(budgetApi.sources).mockResolvedValue([]);
  vi.mocked(budgetApi.revision).mockResolvedValue(revision);
});
afterEach(() => { cleanup(); localStorage.clear(); vi.clearAllMocks(); });
async function openBudget() {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(<QueryClientProvider client={client}><ConstructionBudget projectId="p" userId="u" categories={[]}/></QueryClientProvider>);
  return screen.findByRole('button', { name: 'Nastavení zobrazení' });
}
it('keeps view controls under settings and preserves their saved values', async () => {
  const trigger = await openBudget();
  expect(trigger).toHaveAttribute('aria-expanded', 'false');
  expect(screen.queryByRole('checkbox', { name: 'Zalamovat' })).not.toBeInTheDocument();
  expect(screen.queryByRole('button', { name: 'Sloupce' })).not.toBeInTheDocument();
  expect(screen.getByRole('switch', { name: 'Výkaz výměr' })).toBeVisible();
  fireEvent.click(trigger);
  fireEvent.click(screen.getByRole('checkbox', { name: 'Zalamovat' }));
  fireEvent.click(screen.getByRole('button', { name: 'Pohodlná' }));
  await waitFor(() => expect(JSON.parse(localStorage.getItem('tf-budget-view:u:p')!)).toMatchObject({ wrap: true, density: 60 }));
  fireEvent.keyDown(screen.getByRole('checkbox', { name: 'Zalamovat' }), { key: 'Escape' });
  expect(trigger).toHaveFocus();
  expect(trigger).toHaveAttribute('aria-expanded', 'false');
  fireEvent.click(trigger);
  expect(screen.getByRole('checkbox', { name: 'Zalamovat' })).toBeChecked();
  expect(screen.getByRole('button', { name: 'Pohodlná' })).toHaveAttribute('aria-pressed', 'true');
  fireEvent.pointerDown(document.body);
  expect(trigger).toHaveAttribute('aria-expanded', 'false');
});
it('opens column configuration from settings and restores focus to the settings button', async () => {
  const trigger = await openBudget();
  fireEvent.click(trigger);
  fireEvent.click(screen.getByRole('button', { name: 'Sloupce' }));
  expect(screen.getByRole('dialog', { name: 'Nastavení sloupců' })).toBeVisible();
  expect(trigger).toHaveAttribute('aria-expanded', 'false');
  fireEvent.click(screen.getByRole('checkbox', { name: 'Zobrazit MJ', exact: true }));
  await waitFor(() => expect(JSON.parse(localStorage.getItem('tf-budget-view:u:p')!).columns.find((column: { key: string }) => column.key === 'unit').hidden).toBe(true));
  fireEvent.click(screen.getByRole('button', { name: 'Zavřít dialog' }));
  expect(trigger).toHaveFocus();
});
it('orders columns in their pinned group and restores defaults without losing other view settings', async () => {
  const trigger = await openBudget();
  fireEvent.click(trigger);
  fireEvent.click(screen.getByRole('checkbox', { name: 'Zalamovat' }));
  fireEvent.click(screen.getByRole('button', { name: 'Sloupce' }));
  const dialog = within(screen.getByRole('dialog', { name: 'Nastavení sloupců' }));
  const names = () => dialog.getAllByRole('rowheader').map(row => row.textContent);
  expect(names().slice(0, 4)).toEqual(['Typ', 'Kód', 'Popis', 'MJ']);
  expect(dialog.getByRole('button', { name: 'Posunout Typ nahoru' })).toBeDisabled();
  expect(dialog.getByRole('button', { name: 'Posunout Kód dolů' })).toBeDisabled();
  expect(dialog.getByRole('button', { name: 'Posunout Popis nahoru' })).toBeDisabled();
  fireEvent.click(dialog.getByRole('button', { name: 'Posunout Popis dolů' }));
  expect(names().slice(0, 4)).toEqual(['Typ', 'Kód', 'MJ', 'Popis']);
  fireEvent.click(dialog.getByRole('checkbox', { name: 'Připnout Popis' }));
  expect(names().slice(0, 4)).toEqual(['Typ', 'Kód', 'Popis', 'MJ']);
  fireEvent.click(dialog.getByRole('button', { name: 'Posunout Popis nahoru' }));
  expect(names().slice(0, 3)).toEqual(['Typ', 'Popis', 'Kód']);
  for (const checkbox of dialog.getAllByRole('checkbox', { name: /^Zobrazit / }).slice(1)) fireEvent.click(checkbox);
  expect(dialog.getByRole('checkbox', { name: 'Zobrazit Typ' })).toBeDisabled();
  expect(dialog.getByText('Zobrazeno 1 z 9 sloupců')).toBeVisible();
  fireEvent.click(dialog.getByRole('button', { name: 'Obnovit výchozí' }));
  expect(names().slice(0, 4)).toEqual(['Typ', 'Kód', 'Popis', 'MJ']);
  expect(dialog.getByRole('checkbox', { name: 'Připnout Popis' })).not.toBeChecked();
  expect(dialog.getByText('Zobrazeno 9 z 9 sloupců')).toBeVisible();
  await waitFor(() => expect(JSON.parse(localStorage.getItem('tf-budget-view:u:p')!)).toMatchObject({ wrap: true }));
  fireEvent.click(dialog.getByRole('button', { name: 'Hotovo' }));
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  expect(trigger).toHaveFocus();
});
