import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { pathToFileURL } from 'node:url';
const { PGlite } = await import(pathToFileURL(process.env.PGLITE_MODULE).href);
test('comparison access, retry, concurrency and deletion lifecycle', async () => {
 const db = new PGlite();
 try {
 await db.exec(`CREATE ROLE service_role BYPASSRLS; CREATE ROLE authenticated; CREATE ROLE anon; CREATE ROLE tenderflow_mcp_client; CREATE SCHEMA auth; CREATE SCHEMA private;
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS 'SELECT nullif(current_setting(''test.user'',true),'''')::uuid';
 CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS 'SELECT jsonb_build_object(''role'',current_setting(''test.role'',true))';
 CREATE TABLE auth.users(id uuid PRIMARY KEY);
 CREATE TABLE organizations(id uuid PRIMARY KEY);
 CREATE TABLE projects(id text PRIMARY KEY,organization_id uuid REFERENCES organizations);
 CREATE TABLE organization_members(organization_id uuid,user_id uuid,is_active boolean);
 CREATE TABLE demand_categories(id text PRIMARY KEY,project_id text);
 CREATE FUNCTION public.can_project_module_action(text,text,boolean) RETURNS boolean LANGUAGE sql STABLE AS 'SELECT $1 = current_setting(''test.project'',true) AND (NOT $3 OR current_setting(''test.edit'',true)=''yes'')';
 CREATE FUNCTION public.mcp_has_permission(text) RETURNS boolean LANGUAGE sql STABLE AS 'SELECT current_setting(''test.grant'',true)=''yes''';
 GRANT USAGE ON SCHEMA auth TO authenticated,tenderflow_mcp_client;
 INSERT INTO auth.users VALUES ('00000000-0000-0000-0000-000000000001');
 INSERT INTO organizations VALUES ('00000000-0000-0000-0000-000000000002');
 INSERT INTO projects VALUES ('own','00000000-0000-0000-0000-000000000002'),('foreign','00000000-0000-0000-0000-000000000002');
 INSERT INTO organization_members VALUES ('00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000001',true);
 INSERT INTO demand_categories VALUES ('tender','own'),('wrong','foreign');`);
 await db.exec(readFileSync(new URL('../../supabase/migrations/20260920123012_offer_comparison_views.sql', import.meta.url),'utf8'));
 await db.exec(`CREATE FUNCTION public.is_active_org_admin_or_owner(uuid) RETURNS boolean LANGUAGE sql STABLE AS 'SELECT current_setting(''test.admin'',true)=''yes''';`);
 await db.exec(readFileSync(new URL('../../supabase/migrations/20260920123359_offer_processing_usage.sql', import.meta.url),'utf8'));
 await db.exec(`SELECT set_config('test.user','00000000-0000-0000-0000-000000000001',false),set_config('test.project','own',false),set_config('test.edit','yes',false),set_config('test.role','authenticated',false); SET ROLE authenticated;`);
 const source = { id:'base',name:'file.xlsx',sha256:'a'.repeat(64),notes:[],items:[{id:'row',code:'1',description:'Malba',unit:'m2',quantity:'1',unitPrice:null,total:null,group:'',source:{sheet:'S',row:2}}] };
 const doc = {schemaVersion:1,sources:[source,{...source,id:'offer',name:'offer.xlsx'}],assignments:{offer:[]}};
 const save = (project='own',category='tender',id=null,version=0,title='Test')=>db.query('SELECT public.offer_comparison_save($1,$2,$3,$4,$5,$6,$7) AS result',[project,id,version,'00000000-0000-0000-0000-000000000010',title,category,doc]);
 await assert.rejects(()=>save('foreign'),/denied/);
 await assert.rejects(()=>save('own','wrong'),/Invalid tender/);
 const malformed=structuredClone(doc);malformed.sources[1].id='base';
 await assert.rejects(()=>db.query('SELECT public.offer_comparison_save($1,NULL,0,$2,$3,NULL,$4)',['own','00000000-0000-0000-0000-000000000099','Invalid',malformed]),/Invalid source/);
 const first=(await save()).rows[0].result;
 assert.equal((await save()).rows[0].result.id,first.id);
 await assert.rejects(()=>save('own','tender',null,0,'Changed'),/already used/);
 assert.equal((await save('own','tender',first.id,1)).rows[0].result.version,2);
 await assert.rejects(()=>save('own','tender',first.id,1),/reload/);
 await assert.rejects(()=>db.query('SELECT * FROM public.offer_comparison_views'),/permission denied/);
 await db.exec(`SELECT set_config('test.edit','no',false);`);
 await assert.rejects(()=>save(),/denied/);
 assert.ok((await db.query('SELECT public.offer_comparison_load($1,$2) AS v',['own',first.id])).rows[0].v);
 await db.exec(`RESET ROLE; SELECT set_config('test.role','tenderflow_mcp_client',false),set_config('test.grant','no',false); SET ROLE tenderflow_mcp_client;`);
 await assert.rejects(()=>db.query('SELECT public.offer_comparison_load($1)',['own']),/denied/);
 await db.exec(`RESET ROLE; INSERT INTO public.offer_processing_settings VALUES('00000000-0000-0000-0000-000000000002',true,0.1); SET ROLE service_role;`);
 const reserve=(request,hash='b'.repeat(64))=>db.query('SELECT public.offer_processing_reserve($1,$2,$3,$4,$5,$6,$7,$8) AS r',['own','00000000-0000-0000-0000-000000000001',request,hash,'matching','test-model',0.06,{version:'test'}]);
 const run=(await reserve('00000000-0000-0000-0000-000000000020')).rows[0].r;
 assert.equal((await reserve('00000000-0000-0000-0000-000000000020')).rows[0].r.reused,true);
 await assert.rejects(()=>reserve('00000000-0000-0000-0000-000000000020','c'.repeat(64)),/conflict/);
 await assert.rejects(()=>reserve('00000000-0000-0000-0000-000000000021'),/budget/);
 await db.query('UPDATE public.offer_processing_runs SET estimated_cost_usd=0.01,status=$1,result=$2 WHERE id=$3',['completed',{text:JSON.stringify({suggestions:[{baseId:'a',offerId:'b'}]})},run.runId]);
 await reserve('00000000-0000-0000-0000-000000000021');
 await db.exec(`RESET ROLE; SELECT set_config('test.role','authenticated',false),set_config('test.edit','yes',false); SET ROLE authenticated;`);
 await db.query('SELECT public.offer_processing_feedback_save($1,$2,$3)',[run.runId,'a',true]);
 await assert.rejects(()=>db.query('SELECT public.offer_processing_feedback_save($1,$2,$3)',[run.runId,'foreign',true]),/Unknown/);
 await assert.rejects(()=>db.query('SELECT public.offer_processing_admin($1)',['00000000-0000-0000-0000-000000000002']),/admin/);
 await db.exec(`SELECT set_config('test.admin','yes',false);`);
 const report=(await db.query('SELECT public.offer_processing_admin($1) AS r',['00000000-0000-0000-0000-000000000002'])).rows[0].r;
 assert.equal(report.quality[0].accepted,1);assert.equal(report.runs.length,2);
 assert.equal(report.runs.filter(r=>r.estimated_cost_usd===null).length,1);
 await db.exec(`RESET ROLE;
 ALTER TABLE public.projects ADD owner_id uuid DEFAULT '00000000-0000-0000-0000-000000000001';
 CREATE FUNCTION public.is_org_member(uuid) RETURNS boolean LANGUAGE sql AS 'SELECT true';
 CREATE FUNCTION public.is_org_admin(uuid) RETURNS boolean LANGUAGE sql AS 'SELECT true';
 CREATE FUNCTION private.budget_backup_signature(text) RETURNS text LANGUAGE sql AS 'SELECT md5($1)';
 CREATE FUNCTION private.budget_backup_export(jsonb) RETURNS jsonb LANGUAGE sql AS 'SELECT $1';
 CREATE FUNCTION private.budget_backup_restore(jsonb,uuid,text) RETURNS integer LANGUAGE sql AS 'SELECT 0';`);
 await db.exec(readFileSync(new URL('../../supabase/migrations/20260920123919_offer_comparison_backup.sql', import.meta.url),'utf8'));
 const manifest={organization_id:'00000000-0000-0000-0000-000000000002',projects:[{id:'own'}]};
 const backup=(await db.query('SELECT private.budget_backup_export($1) AS b',[manifest])).rows[0].b;
 assert.equal(backup.offer_comparisons.length,1);
 await db.exec('DELETE FROM public.offer_comparison_views');
 await db.query('SELECT private.budget_backup_restore($1,$2,$3)',[backup,manifest.organization_id,'user']);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM public.offer_comparison_views')).rows[0].n,1);
 const tampered=structuredClone(backup);tampered.offer_comparisons[0].signature='bad';
 await assert.rejects(()=>db.query('SELECT private.budget_backup_restore($1,$2,$3)',[tampered,manifest.organization_id,'user']),/signature/);
 await db.exec(`RESET ROLE; DELETE FROM auth.users;`);
 assert.equal((await db.query('SELECT created_by FROM public.offer_comparison_views')).rows[0].created_by,null);
 await db.exec(`DELETE FROM projects WHERE id='own'`);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM public.offer_comparison_views')).rows[0].n,0);
 } finally { await db.close(); }
});
