// @ts-check

export const MCP_PERMISSION_IDS = Object.freeze({
  read: "tenderflow.read",
  contactsRead: "tenderflow.contacts.read",
  write: "tenderflow.write",
  bidOfferWrite: "tenderflow.bids.offer.write",
});

const READ = Object.freeze([MCP_PERMISSION_IDS.read]);
const CONTACTS = Object.freeze([MCP_PERMISSION_IDS.read, MCP_PERMISSION_IDS.contactsRead]);
const WRITE = Object.freeze([MCP_PERMISSION_IDS.read, MCP_PERMISSION_IDS.write]);
const BID_OFFER_WRITE = Object.freeze([
  MCP_PERMISSION_IDS.read,
  MCP_PERMISSION_IDS.write,
  MCP_PERMISSION_IDS.bidOfferWrite,
]);

/**
 * Shared, presentation-safe MCP catalog. It contains no secrets, grants, user data,
 * handlers, or database access. Server authorization and the settings matrix both
 * consume this list so a newly added tool cannot silently drift between them.
 */
export const MCP_TOOL_CATALOG = Object.freeze([
  {
    name: "search",
    title: "Vyhledávání Tender Flow",
    category: "Vyhledávání",
    data: "Stavby, výběrová řízení a osobní úkoly; kontakty jen s rozšířeným grantem.",
    requiredPermissions: READ,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "fetch",
    title: "Načtení výsledku",
    category: "Vyhledávání",
    data: "Detail výsledku vráceného vyhledáváním; kontakt jen s rozšířeným grantem.",
    requiredPermissions: READ,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_list_projects",
    title: "Seznam staveb",
    category: "Stavby",
    data: "Názvy, lokality, stav a termíny projektů dostupných přihlášenému uživateli.",
    requiredPermissions: READ,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_get_project_summary",
    title: "Souhrn stavby",
    category: "Stavby",
    data: "Minimalizovaný souhrn stavby, agregace nabídek, smlouvy a plán bez kontaktního PII.",
    requiredPermissions: READ,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_get_project_detail",
    title: "Detail stavby",
    category: "Stavby",
    data: "Detail stavby včetně výběrových řízení, nabídek, smluv a plánu.",
    requiredPermissions: CONTACTS,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_list_tenders",
    title: "Výběrová řízení",
    category: "Výběrová řízení",
    data: "Poptávkové kategorie a jejich stav, volitelně omezené na jednu stavbu.",
    requiredPermissions: READ,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_list_bids",
    title: "Nabídky dodavatelů",
    category: "Výběrová řízení",
    data: "Nabídky a jejich dodavatelé, ceny a kontaktní detaily v rámci oprávnění uživatele.",
    requiredPermissions: CONTACTS,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_list_winners",
    title: "Vítězné nabídky",
    category: "Výběrová řízení",
    data: "Vítězné nebo zasmluvněné nabídky a údaje jejich dodavatelů.",
    requiredPermissions: CONTACTS,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_list_contracts",
    title: "Seznam smluv",
    category: "Smlouvy",
    data: "Smlouvy viditelné uživateli, volitelně omezené na jednu stavbu.",
    requiredPermissions: READ,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_get_contract_overview",
    title: "Smluvní přehled",
    category: "Smlouvy",
    data: "Organizační přehled smluv bez interních cest k dokumentům.",
    requiredPermissions: READ,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_list_tender_plan",
    title: "Plán výběrových řízení",
    category: "Plánování",
    data: "Termíny a položky harmonogramu výběrových řízení.",
    requiredPermissions: READ,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_list_upcoming_deadlines",
    title: "Blížící se termíny",
    category: "Plánování",
    data: "Nejbližší termíny výběrových řízení na dostupných stavbách.",
    requiredPermissions: READ,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_list_tasks",
    title: "Osobní úkoly",
    category: "Úkoly",
    data: "Pouze úkoly vlastněné přihlášeným uživatelem, bez metadat externích providerů.",
    requiredPermissions: READ,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_list_contacts",
    title: "Kontakty",
    category: "Kontaktní údaje",
    data: "Firmy, osoby, e-maily a telefony v rozsahu rolí a tenantového přístupu uživatele.",
    requiredPermissions: CONTACTS,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_match_outlook_reply",
    title: "Přiřazení odpovědi z Outlooku",
    category: "Emaily",
    data: "Najde kartu dodavatele podle immutable Outlook ID, internetMessageId, In-Reply-To nebo conversationId; obsah emailu se neukládá.",
    requiredPermissions: CONTACTS,
    riskLevel: "low",
    mode: "read",
  },
  {
    name: "tf_link_outlook_message",
    title: "Propojení Outlook zprávy",
    category: "Emaily",
    data: "Idempotentně propojí stabilní Outlook identifikátory s jednou kartou dodavatele; nemění cenu ani stav nabídky.",
    requiredPermissions: WRITE,
    riskLevel: "medium",
    mode: "write",
  },
  {
    name: "tf_prepare_bid_status_change",
    title: "Příprava přesunu karty dodavatele",
    category: "Zápis",
    data: "Připraví změnu stavu karty dodavatele v kanbanu; stav změní až následné potvrzení a provedení.",
    requiredPermissions: WRITE,
    riskLevel: "medium",
    mode: "write",
  },
  {
    name: "tf_prepare_bid_offer_update",
    title: "Příprava ceny nabídky",
    category: "Zápis",
    data: "Připraví cenu nabídky bez DPH v CZK a připojí důležité podmínky do poznámky karty; změnu provede až následné potvrzení.",
    requiredPermissions: BID_OFFER_WRITE,
    riskLevel: "medium",
    mode: "write",
  },
  {
    name: "tf_prepare_change",
    title: "Příprava změny",
    category: "Zápis",
    data: "Vytvoří návrh podporované změny; obchodní data ještě nemění.",
    requiredPermissions: WRITE,
    riskLevel: "medium",
    mode: "write",
  },
  {
    name: "tf_confirm_change",
    title: "Potvrzení změny",
    category: "Zápis",
    data: "Ověří přesný potvrzovací text a vrátí jej pro provedení změny.",
    requiredPermissions: WRITE,
    riskLevel: "high",
    mode: "write",
  },
  {
    name: "tf_execute_change",
    title: "Provedení změny",
    category: "Zápis",
    data: "Provede potvrzenou změnu se stejným potvrzovacím textem a idempotency klíčem; starší tokeny zůstávají kompatibilní.",
    requiredPermissions: WRITE,
    riskLevel: "high",
    mode: "write",
  },
]);
