import type { HelpEntry } from "../types";

export const contactsHelp: HelpEntry[] = [
  {
    id: "contacts-list",
    view: "contacts",
    label: "Seznam subdodavatelů",
    description: "Hlavní seznam všech subdodavatelů/kontaktů v systému. Můžete vyhledávat, filtrovat podle specializace a řadit.",
    detail: "Každý kontakt má firmu, specializace, hodnocení hvězdičkami, stav a kontaktní osoby. Kliknutím na řádek otevřete detail pro editaci. Zaškrtávacími políčky můžete vybrat více kontaktů pro hromadné akce.",
    category: "info",
    tourOrder: 1,
  },
  {
    id: "contacts-add",
    view: "contacts",
    label: "Přidat subdodavatele",
    description: "Vytvoří nový záznam subdodavatele. Povinné údaje: název firmy a alespoň jedna specializace.",
    category: "action",
    tourOrder: 2,
    dataFlow: [
      { targetHelpId: "contacts-list", label: "Nový kontakt se objeví v seznamu" },
    ],
  },
  {
    id: "contacts-bulk-actions",
    view: "contacts",
    label: "Hromadné akce",
    description: "Po výběru více kontaktů se zobrazí lišta s hromadnými akcemi — smazání a automatické doplnění adres.",
    detail: "Auto-doplnění adres využívá IČO k vyhledání sídla firmy v obchodním rejstříku (ARES). Webové stránky se dohledávají automaticky pomocí AI u kontaktů s vyplněným IČO. Smazání vyžaduje potvrzení.",
    category: "action",
    tourOrder: 3,
  },
  {
    id: "contacts-company-field",
    view: "contacts",
    label: "Název firmy",
    description: "Povinné pole — oficiální název společnosti subdodavatele. Validuje se formát názvu.",
    category: "data-entry",
    tourOrder: 4,
  },
  {
    id: "contacts-specialization",
    view: "contacts",
    label: "Specializace",
    description: "Obory činnosti subdodavatele (např. Elektroinstalace, ZTI, Vzduchotechnika). Můžete vybrat z nabídky nebo zadat vlastní.",
    detail: "Specializace slouží k filtrování kontaktů při hledání subdodavatelů pro konkrétní poptávkovou kategorii. Jeden kontakt může mít více specializací.",
    category: "data-entry",
    tourOrder: 5,
    dataFlow: [
      { targetHelpId: "pipeline-kanban", label: "Používá se při výběru subdodavatelů v Pipeline" },
    ],
  },
  {
    id: "contacts-ico",
    view: "contacts",
    label: "IČO a vyhledání",
    description: "Identifikační číslo organizace. Tlačítkem vedle můžete automaticky vyhledat údaje firmy v rejstřících (ARES, RŽP).",
    detail: "Po zadání IČO a kliknutí na 'Vyhledat' se automaticky doplní adresa a další údaje z veřejných rejstříků. Odkazy na ARES, RŽP a RES se zobrazí pod formulářem.",
    category: "data-entry",
    tourOrder: 6,
  },
  {
    id: "contacts-web",
    view: "contacts",
    label: "Webová stránka",
    description: "URL webové stránky subdodavatele. Pokud má kontakt vyplněné IČO a web chybí, systém se pokusí web automaticky dohledat pomocí AI.",
    detail: "Automatické dohledání probíhá na pozadí při otevření seznamu kontaktů i po uložení nového kontaktu. Dohledaný web se uloží přímo ke kontaktu. Pokud AI web nenajde, pole zůstane prázdné a lze ho vyplnit ručně.",
    category: "data-entry",
    tourOrder: 7,
  },
  {
    id: "contacts-regions",
    view: "contacts",
    label: "Kraje působnosti",
    description: "Výběr krajů ČR, ve kterých subdodavatel působí. Tlačítko 'Celá ČR' zaškrtne všechny kraje najednou.",
    detail: "Kraje slouží k filtrování subdodavatelů podle lokality stavby. Při výběru dodavatele pro konkrétní projekt tak snadno najdete firmy, které působí v daném regionu. Lze vybrat libovolnou kombinaci krajů.",
    category: "data-entry",
    tourOrder: 8,
    dataFlow: [
      { targetHelpId: "pipeline-kanban", label: "Filtrování dodavatelů podle lokality stavby" },
    ],
  },
  {
    id: "contacts-note",
    view: "contacts",
    label: "Poznámka",
    description: "Volné textové pole pro vlastní poznámky k subdodavateli — zkušenosti z předchozích zakázek, specifické podmínky apod.",
    category: "data-entry",
    tourOrder: 9,
  },
  {
    id: "contacts-persons",
    view: "contacts",
    label: "Kontaktní osoby",
    description: "Seznam kontaktních osob subdodavatele — jméno, pozice, telefon, e-mail. Jeden subdodavatel může mít více kontaktů.",
    category: "data-entry",
    tourOrder: 10,
  },
  {
    id: "contacts-rating",
    view: "contacts",
    label: "Hodnocení",
    description: "Hvězdičkové hodnocení subdodavatele (1-5). Slouží k internímu posouzení kvality a spolehlivosti.",
    detail: "Hodnocení se zobrazuje v seznamu kontaktů i při výběru subdodavatelů v Pipeline. Pomáhá rychle identifikovat preferované dodavatele.",
    category: "data-entry",
    tourOrder: 11,
  },
];
