import type { HelpEntry } from "../types";

export const dashboardHelp: HelpEntry[] = [
  {
    id: "dashboard-project-selector",
    view: "dashboard",
    label: "Výběr projektu",
    description: "Vyberte aktivní projekt, jehož přehled chcete zobrazit. Dashboard vždy zobrazuje data jednoho konkrétního projektu.",
    detail: "Poslední vybraný projekt se ukládá do paměti prohlížeče, takže při dalším otevření Dashboardu se automaticky zobrazí. Seznam obsahuje pouze aktivní (nearchivované) projekty.",
    category: "navigation",
    tourOrder: 1,
  },
  {
    id: "dashboard-export",
    view: "dashboard",
    label: "Export přehledu",
    description: "Exportuje souhrnný přehled projektu do Excel souboru (.xlsx) — obsahuje všechny poptávkové kategorie, rozpočty, nabídky a vítěze.",
    detail: "Exportovaný soubor obsahuje sloupce: Stav, Poptávka, SOD cena, Plán cena, Cena VŘ, rozdíly SOD-VŘ a PN-VŘ, počty nabídek a vítěze. Vhodné pro reporting a sdílení s kolegy.",
    category: "action",
    tourOrder: 2,
    dataFlow: [
      { targetHelpId: "dashboard-overview", label: "Data z přehledu projektu → Excel soubor" },
    ],
  },
  {
    id: "dashboard-overview",
    view: "dashboard",
    label: "Přehled projektu",
    description: "Hlavní oblast zobrazující detailní metriky a statistiky vybraného projektu — rozpočty, finanční přehled, stav poptávek a nabídek.",
    detail: "Přehled obsahuje: rozpočet investora (celková cena SOD), interní rozpočet (plánované náklady), finanční podmínky, seznam poptávkových kategorií s cenami a nabídkami. Data se načítají ze záložky Plán VŘ a Pipeline daného projektu.",
    category: "info",
    tourOrder: 3,
    dataFlow: [
      { targetHelpId: "dashboard-project-selector", label: "Závisí na vybraném projektu" },
    ],
  },
  {
    id: "dashboard-budget-section",
    view: "dashboard",
    label: "Rozpočet (Investor)",
    description: "Základní cena SOD — celkový rozpočet projektu od investora. Tvoří základ pro výpočet úspor z výběrových řízení.",
    detail: "Rozpočet investora se zadává v detailech projektu. Rozdíl mezi SOD cenou a cenou z VŘ (výběrového řízení) ukazuje, kolik se podařilo ušetřit oproti původnímu rozpočtu.",
    category: "info",
    tourOrder: 4,
  },
  {
    id: "dashboard-internal-budget",
    view: "dashboard",
    label: "Interní rozpočet",
    description: "Plánované interní náklady projektu. Slouží k porovnání s cenami z výběrových řízení.",
    detail: "Interní rozpočet se skládá z plánovaných částek jednotlivých poptávkových kategorií. Rozdíl PN-VŘ (Plán - Výběrové řízení) ukazuje úsporu oproti internímu plánu.",
    category: "info",
    tourOrder: 5,
  },
  {
    id: "dashboard-demands-table",
    view: "dashboard",
    label: "Přehled poptávek",
    description: "Tabulka všech poptávkových kategorií projektu — zobrazuje stav, ceny SOD, plánované ceny, ceny z VŘ, rozdíly a počty nabídek.",
    detail: "Každý řádek představuje jednu poptávkovou kategorii (např. 'Elektroinstalace', 'ZTI'). Sloupce ukazují: stav (Probíhá/SOD/Ukončeno), rozpočtové ceny, skutečnou cenu z VŘ, finanční rozdíly a počet přijatých nabídek. Kliknutím na řádek přejdete do Pipeline dané kategorie.",
    category: "data-flow",
    tourOrder: 6,
    dataFlow: [
      { targetHelpId: "dashboard-budget-section", label: "Součty tvoří celkový rozpočet" },
    ],
  },
  {
    id: "dashboard-financial-conditions",
    view: "dashboard",
    label: "Finanční podmínky",
    description: "Smluvní finanční podmínky projektu — zálohy, splatnosti, garance, pojištění a další finanční parametry.",
    category: "info",
    tourOrder: 7,
  },
];
