import type { HelpEntry } from "../types";

export const projectHelp: HelpEntry[] = [
  // === PROJECT LAYOUT (tabs navigation) ===
  {
    id: "project-tabs",
    view: "project",
    label: "Záložky projektu",
    description: "Přepínání mezi hlavními sekcemi projektu. Každá záložka zobrazuje jiný pohled na data stavby.",
    detail: "Přehled = souhrn a finance, Plán VŘ = harmonogram výběrových řízení, Výběrová řízení = pipeline nabídek, Harmonogram = Ganttův diagram, Dokumenty = správa souborů, Smlouvy = správa smluvní dokumentace.",
    category: "navigation",
    tourOrder: 1,
  },

  // === OVERVIEW TAB ===
  {
    id: "overview-kpi-cards",
    view: "project",
    tab: "overview",
    label: "Klíčové ukazatele (KPI)",
    description: "Čtyři hlavní metriky projektu: Rozpočet investora, Plán nákladů, Zasmluvněná částka a Postup výběrových řízení.",
    detail: "Rozpočet = celková cena SOD od investora. Plán = interní plánované náklady. Zasmluvněno = kolik je pokryto smlouvami. Postup VŘ = procento dokončených výběrových řízení z celkového počtu.",
    category: "info",
    tourOrder: 2,
  },
  {
    id: "overview-building-info",
    view: "project",
    tab: "overview",
    label: "Údaje o stavbě",
    description: "Základní informace o projektu — investor, místo stavby, termín dokončení, stavbyvedoucí.",
    detail: "Tyto údaje se zadávají při vytvoření projektu a lze je editovat kliknutím na ikonu tužky. Slouží pro rychlou identifikaci stavby.",
    category: "data-entry",
    tourOrder: 3,
  },
  {
    id: "overview-investor-finances",
    view: "project",
    tab: "overview",
    label: "Finance investora",
    description: "Finanční přehled ze strany investora — základní cena SOD, dodatky a celkový rozpočet stavby.",
    detail: "SOD = Smlouva o dílo. Dodatky navyšují nebo snižují původní cenu. Celkový rozpočet = SOD základ + součet všech dodatků. Tyto hodnoty se automaticky počítají z poptávkových kategorií.",
    category: "info",
    tourOrder: 4,
    dataFlow: [
      { targetHelpId: "overview-demand-table", label: "Součty z poptávkových kategorií" },
    ],
  },
  {
    id: "overview-internal-budget",
    view: "project",
    tab: "overview",
    label: "Interní rozpočet",
    description: "Plánované náklady, zasmluvněná částka a rezerva. Slouží k internímu sledování ekonomiky projektu.",
    detail: "Plán = cílové náklady podle interního rozpočtu. Zasmluvněno = součet cen z uzavřených smluv/SOD. Rezerva = rozdíl mezi plánem a zasmluvněnou částkou.",
    category: "info",
    tourOrder: 5,
  },
  {
    id: "overview-contract-params",
    view: "project",
    tab: "overview",
    label: "Parametry smlouvy",
    description: "Smluvní podmínky — splatnost, záruční doba, zádržné, platební podmínky, pojištění a další finanční parametry.",
    category: "info",
    tourOrder: 6,
  },
  {
    id: "overview-demand-table",
    view: "project",
    tab: "overview",
    label: "Přehled poptávek",
    description: "Tabulka všech poptávkových kategorií s cenami, nabídkami a stavy. Kliknutím přejdete do Pipeline dané kategorie.",
    detail: "Každý řádek je jedna poptávková kategorie (např. Elektroinstalace). Zobrazuje cenu SOD, plán, cenu z VŘ, rozdíly a počet nabídek. Barva stavu indikuje fázi: zelená = zasmluvněno, modrá = probíhá, šedá = ukončeno.",
    category: "data-flow",
    tourOrder: 7,
    dataFlow: [
      { targetHelpId: "overview-investor-finances", label: "Součty tvoří celkový rozpočet" },
    ],
  },

  // === TENDER PLAN TAB ===
  {
    id: "tender-plan-sidebar",
    view: "project",
    tab: "tender-plan",
    label: "Navigace plánu VŘ",
    description: "Filtrování výběrových řízení podle stavu — všechna, probíhající, ukončená. Také přístup k nástrojům pro import a export.",
    category: "navigation",
    tourOrder: 1,
  },
  {
    id: "tender-plan-add",
    view: "project",
    tab: "tender-plan",
    label: "Nové výběrové řízení",
    description: "Vytvoří nový záznam v plánu výběrových řízení. Zadáte název, datum zahájení a ukončení.",
    detail: "Každé VŘ v plánu odpovídá jedné poptávkové kategorii. Po vytvoření se automaticky propojí s Pipeline, kde můžete spravovat nabídky subdodavatelů.",
    category: "action",
    tourOrder: 2,
    dataFlow: [
      { targetHelpId: "tender-plan-table", label: "Nový řádek v tabulce" },
    ],
  },
  {
    id: "tender-plan-table",
    view: "project",
    tab: "tender-plan",
    label: "Tabulka výběrových řízení",
    description: "Přehled všech VŘ projektu — název, termíny (od-do), stav propojené poptávky a akční tlačítka.",
    detail: "Sloupec 'Poptávka' ukazuje, zda je VŘ propojeno s kategorií v Pipeline a její aktuální stav. Akce: editace termínů, smazání záznamu. Data se také zobrazují v záložce Harmonogram.",
    category: "info",
    tourOrder: 3,
    dataFlow: [
      { targetHelpId: "tender-plan-sidebar", label: "Filtrováno podle vybraného stavu" },
    ],
  },
  {
    id: "tender-plan-tools",
    view: "project",
    tab: "tender-plan",
    label: "Nástroje a import",
    description: "Import plánu z Excelu, synchronizace s existujícími kategoriemi a export do Excelu.",
    detail: "Import: nahrajte Excel soubor se sloupci Název, Od, Do. Synchronizace: automaticky vytvoří záznamy pro existující poptávkové kategorie, které ještě nemají VŘ. Export: stáhne aktuální plán jako Excel.",
    category: "action",
    tourOrder: 4,
  },

  // === PIPELINE TAB ===
  {
    id: "pipeline-filters",
    view: "project",
    tab: "pipeline",
    label: "Filtry a zobrazení",
    description: "Filtrování poptávkových kategorií podle stavu (Poptávané/Ukončené/Zasmluvněné) a přepínání mezi mřížkou a tabulkou.",
    category: "navigation",
    tourOrder: 1,
  },
  {
    id: "pipeline-add-category",
    view: "project",
    tab: "pipeline",
    label: "Nová poptávka",
    description: "Vytvoří novou poptávkovou kategorii (např. Elektroinstalace, ZTI, Vzduchotechnika).",
    detail: "Poptávková kategorie reprezentuje jeden typ práce, na který hledáte subdodavatele. Zadáváte název, rozpočet SOD, plánovaný rozpočet a termíny. Maximum 5 dodavatelů na kategorii.",
    category: "action",
    tourOrder: 2,
  },
  {
    id: "pipeline-category-card",
    view: "project",
    tab: "pipeline",
    label: "Karty poptávek",
    description: "Mřížka poptávkových kategorií — každá karta zobrazuje stav, termín, počty nabídek a akce.",
    detail: "Kliknutím na kartu otevřete detail s Kanban boardem nabídek. Barva stavu: modrá = probíhá, zelená = zasmluvněno, šedá = ukončeno. Ikony akcí: dokončit, editovat, smazat. Přepněte na tabulkový pohled tlačítky vpravo nahoře.",
    category: "info",
    tourOrder: 3,
    dataFlow: [
      { targetHelpId: "overview-demand-table", label: "Součty se promítají do přehledu projektu" },
    ],
  },
  {
    id: "pipeline-kanban",
    view: "project",
    tab: "pipeline",
    label: "Kanban board nabídek",
    description: "Přehled celého výběrového řízení v jednom pohledu. Každý sloupec představuje jednu fázi procesu. Karty dodavatelů přetahujete mezi sloupci.",
    detail: "Postup výběrového řízení: 1) Oslovení — první kontakt s dodavatelem. 2) Odesláno — poptávka odeslána. 3) Cenová nabídka — dodavatel zaslal cenu. 4) Užší výběr — předvýběr kandidátů. 5) Jednání o SOD — finální vyjednávání. 6) Zamítnuto/Odstoupili — neúspěšní dodavatelé. Přetažením karty měníte fázi.",
    category: "data-flow",
    tourOrder: 4,
    dataFlow: [
      { targetHelpId: "pipeline-category-card", label: "Nabídky patří do poptávkové kategorie" },
      { targetHelpId: "overview-demand-table", label: "Výsledné ceny se promítají do přehledu" },
    ],
  },
  {
    id: "kanban-add-supplier",
    view: "project",
    tab: "pipeline",
    label: "Přidat dodavatele",
    description: "Přidá nového subdodavatele do tohoto výběrového řízení. Vybíráte z existujících kontaktů v databázi.",
    detail: "Otevře se okno s výběrem subdodavatele ze seznamu kontaktů. Můžete vyhledávat podle názvu firmy nebo specializace. Po výběru se dodavatel přidá do sloupce 'Oslovení'. Jeden dodavatel může být max. v jedné fázi současně. Maximum 5 dodavatelů na kategorii.",
    category: "action",
    tourOrder: 5,
    dataFlow: [
      { targetHelpId: "kanban-col-contacted", label: "Nový dodavatel se objeví ve sloupci Oslovení" },
    ],
  },
  {
    id: "kanban-info-bar",
    view: "project",
    tab: "pipeline",
    label: "Informační lišta",
    description: "Zobrazuje název poptávkové kategorie, cenu SOD (od investora) a interní plánovanou cenu.",
    detail: "Cena SOD = částka ze smlouvy o dílo s investorem pro tuto kategorii prací. Interní plán = vaše plánované náklady. Rozdíl mezi těmito cenami a skutečnou cenou z VŘ ukazuje úsporu projektu.",
    category: "info",
    tourOrder: 6,
  },
  {
    id: "kanban-col-contacted",
    view: "project",
    tab: "pipeline",
    label: "Sloupec: Oslovení",
    description: "První fáze — sem se automaticky přidávají noví dodavatelé. Znamená, že jste dodavatele kontaktovali nebo plánujete kontaktovat.",
    detail: "Typický postup: po přidání dodavatele mu odešlete poptávkový email (pomocí tlačítka na kartě). Poté kartu přetáhněte do 'Odesláno'. Pokud dodavatel nemá zájem, přetáhněte do 'Zamítnuto'.",
    category: "data-flow",
    tourOrder: 7,
  },
  {
    id: "kanban-col-offer",
    view: "project",
    tab: "pipeline",
    label: "Sloupec: Cenová nabídka",
    description: "Dodavatel zaslal cenovou nabídku. Dvojklikem na kartu můžete zadat cenu a další údaje nabídky.",
    detail: "Po přetažení karty sem otevřete editaci (dvojklik nebo ikona tužky) a vyplňte: cenu nabídky, poznámky, kontaktní osobu. Cena se zobrazí přímo na kartě. Můžete zadat i více kol nabídek (cenové vyjednávání).",
    category: "data-flow",
    tourOrder: 8,
  },
  {
    id: "kanban-col-sod",
    view: "project",
    tab: "pipeline",
    label: "Sloupec: Jednání o SOD",
    description: "Finální fáze — vybraný dodavatel, se kterým jednáte o smlouvě o dílo. Ikona trofeje označuje vítěze.",
    detail: "Na kartě v tomto sloupci se zobrazí: trofej (vítěz VŘ), tlačítko 'Zasmluvnit' (smlouva ikona) a tlačítko '+' pro vytvoření smlouvy v záložce Smlouvy. Po zasmluvnění se cena promítne do celkového přehledu projektu.",
    category: "data-flow",
    tourOrder: 9,
    dataFlow: [
      { targetHelpId: "contracts-list", label: "Vytvoření smlouvy v záložce Smlouvy" },
      { targetHelpId: "overview-internal-budget", label: "Cena se promítne do zasmluvněné částky" },
    ],
  },
  {
    id: "kanban-bid-card",
    view: "project",
    tab: "pipeline",
    label: "Karta dodavatele",
    description: "Každá karta představuje jednoho subdodavatele a jeho nabídku. Přetahováním mezi sloupci měníte fázi.",
    detail: "Akce na kartě: Přetažení = změna fáze. Dvojklik = editace (cena, poznámky, kontakt). Ikona tužky = editace. Ikona koše = smazání. Ikona dopisu = generování poptávkového emailu. Na kartě vidíte: název firmy, cenu nabídky, kontaktní osobu, telefon a email.",
    category: "info",
    tourOrder: 10,
  },
  {
    id: "kanban-export",
    view: "project",
    tab: "pipeline",
    label: "Export výběrového řízení",
    description: "Export celého výběrového řízení do Excel, Markdown nebo PDF formátu.",
    detail: "Excel (.xlsx) = tabulka se všemi dodavateli, cenami a stavy. Markdown (.md) = textový formát pro sdílení. PDF = formátovaný dokument pro tisk a archivaci.",
    category: "action",
    tourOrder: 11,
  },

  // === SCHEDULE TAB ===
  {
    id: "schedule-controls",
    view: "project",
    tab: "schedule",
    label: "Ovládání harmonogramu",
    description: "Přiblížení (měsíce/týdny/dny), přepnutí režimu editace a zobrazení realizačních termínů.",
    category: "navigation",
    tourOrder: 1,
  },
  {
    id: "schedule-gantt",
    view: "project",
    tab: "schedule",
    label: "Ganttův diagram",
    description: "Vizuální časový plán projektu. Každý řádek je jedno výběrové řízení s barem označujícím dobu trvání.",
    detail: "Červená svislá čára = dnešní datum. Modré bary = plánované termíny VŘ. Zelené bary = realizační termíny. Kliknutím na bar v editačním režimu můžete měnit termíny. Data se načítají z Plánu VŘ.",
    category: "info",
    tourOrder: 2,
    dataFlow: [
      { targetHelpId: "tender-plan-table", label: "Termíny z Plánu VŘ" },
    ],
  },
  {
    id: "schedule-export",
    view: "project",
    tab: "schedule",
    label: "Export harmonogramu",
    description: "Stažení harmonogramu jako Excel nebo PDF soubor pro sdílení a tisk.",
    category: "action",
    tourOrder: 3,
  },

  // === DOCUMENTS TAB ===
  {
    id: "documents-sidebar",
    view: "project",
    tab: "documents",
    label: "Navigace dokumentů",
    description: "Přepínání mezi sekcemi: Projektová dokumentace, Šablony emailů, Složkomat a Ceníky.",
    category: "navigation",
    tourOrder: 1,
  },
  {
    id: "documents-pd",
    view: "project",
    tab: "documents",
    label: "Projektová dokumentace",
    description: "Odkaz na umístění projektové dokumentace — složka na Google Drive, OneDrive nebo lokálním disku.",
    detail: "Zadejte odkaz na složku s PD. Odkaz se uloží a bude přístupný všem členům projektu. Můžete přidat více odkazů s popiskem a datem. Pokud je napojen Složkomat, zobrazí se i rychlý odkaz na PD složku.",
    category: "data-entry",
    tourOrder: 2,
  },

  // --- ŠABLONY EMAILŮ (Templates) ---
  {
    id: "templates-section",
    view: "project",
    tab: "documents",
    label: "Šablony emailů",
    description: "Nastavení šablon pro 3 typy emailové komunikace: poptávkový dopis, materiálová poptávka a email nevybraným dodavatelům.",
    detail: "Každý typ emailu může mít vlastní šablonu s proměnnými (název stavby, lokace, kontakty). Šablony se vytvářejí ve vestavěném editoru s náhledem. Pokud šablona není nastavena, použije se výchozí text.",
    category: "info",
    tourOrder: 3,
  },
  {
    id: "templates-inquiry",
    view: "project",
    tab: "documents",
    label: "Šablona poptávek",
    description: "Šablona pro generování poptávkového emailu subdodavatelům. Použije se při akci 'Generovat poptávku' na kartě dodavatele v Pipeline.",
    detail: "Klikněte na 'Vybrat' pro otevření Správce šablon. Zde můžete: vytvořit novou šablonu, editovat existující (HTML editor s formátováním), vložit proměnné ({NAZEV_STAVBY}, {LOKACE_STAVBY} atd.) a zobrazit náhled. Šablona se použije při generování poptávky z Kanban boardu.",
    category: "data-entry",
    tourOrder: 4,
    dataFlow: [
      { targetHelpId: "kanban-bid-card", label: "Použije se při 'Generovat poptávku' na kartě dodavatele" },
    ],
  },
  {
    id: "templates-material",
    view: "project",
    tab: "documents",
    label: "Šablona materiálové poptávky",
    description: "Šablona pro generování materiálové poptávky. Použije se při akci 'Materiálová poptávka' na kartě dodavatele.",
    detail: "Oddělená šablona pro poptávky materiálů (ne prací). Funguje stejně jako šablona poptávek — má vlastní editor s proměnnými a náhledem.",
    category: "data-entry",
    tourOrder: 5,
  },
  {
    id: "templates-losers",
    view: "project",
    tab: "documents",
    label: "Šablona emailu nevybraným",
    description: "Šablona pro email nevybraným dodavatelům po ukončení výběrového řízení. Obsahuje poděkování a info o výsledku.",
    detail: "Použije se při kliknutí na 'Email nevybraným' v hlavičce kanban boardu. Email se odešle všem dodavatelům, kteří nebyli vybráni. Pokud šablona není nastavena, použije se výchozí text.",
    category: "data-entry",
    tourOrder: 6,
    dataFlow: [
      { targetHelpId: "pipeline-kanban", label: "Tlačítko 'Email nevybraným' v kanban headeru" },
    ],
  },

  // --- SLOŽKOMAT (DocHub) ---
  {
    id: "dochub-status",
    view: "project",
    tab: "documents",
    label: "Stav Složkomatu",
    description: "Zobrazuje aktuální stav napojení — poskytovatel (Google Drive / Desktop), režim a kořenová složka projektu.",
    detail: "Pokud je Složkomat napojen, zobrazí se badge poskytovatele, režim (Můj účet / Organizace) a cesta ke kořenové složce. Tlačítkem 'Otevřít root' otevřete hlavní složku projektu v průzkumníku nebo prohlížeči.",
    category: "info",
    tourOrder: 7,
  },
  {
    id: "dochub-setup",
    view: "project",
    tab: "documents",
    label: "Nastavení Složkomatu",
    description: "Průvodce napojením Složkomatu — výběr poskytovatele (Google Drive nebo lokální disk) a nastavení kořenové složky projektu.",
    detail: "Krok 1: Vyberte poskytovatele — Google Drive (přes OAuth) nebo Tender Flow Desktop (lokální/síťový disk). Krok 2: Zadejte cestu ke kořenové složce — u Google Drive vložte URL složky, u lokálního disku klikněte 'Procházet'. Po připojení Složkomat automaticky spravuje složkovou strukturu projektu.",
    category: "action",
    tourOrder: 8,
  },
  {
    id: "dochub-structure",
    view: "project",
    tab: "documents",
    label: "Struktura složek",
    description: "Editor složkové struktury projektu — definujte, jaké složky se automaticky vytvoří pro každou poptávkovou kategorii.",
    detail: "Klikněte 'Upravit strukturu' pro zobrazení editoru. Můžete: přidávat/odebírat složky, měnit pořadí (šipky nahoru/dolů), vnořovat (odsadit/předsadit), přejmenovat. Dynamické složky (kategorie, dodavatel) se automaticky opakují pro každý záznam. Tlačítko 'Synchronizovat' spustí vytvoření chybějících složek. Strukturu lze uložit jako předvolbu pro další projekty.",
    category: "data-entry",
    tourOrder: 9,
    dataFlow: [
      { targetHelpId: "dochub-autocreate", label: "Struktura definuje, co se vytvoří" },
    ],
  },
  {
    id: "dochub-links",
    view: "project",
    tab: "documents",
    label: "Odkazy na složky",
    description: "Rychlé odkazy na hlavní složky projektu — PD, nabídky, smlouvy, realizace, archiv.",
    detail: "Kliknutím na odkaz otevřete příslušnou složku. U Google Drive se otevře v prohlížeči, u lokálního disku v průzkumníku souborů. Ikona kopírování zkopíruje cestu do schránky.",
    category: "navigation",
    tourOrder: 10,
  },
  {
    id: "dochub-autocreate",
    view: "project",
    tab: "documents",
    label: "Automatické vytváření složek",
    description: "Sledování průběhu a výsledků automatického vytváření složek. Zobrazuje postup, log běhu a přehled vytvořených složek.",
    detail: "Při spuštění synchronizace se zobrazí: progress bar s aktuálním krokem, počet vytvořených/zkontrolovaných složek. Po dokončení: log s detaily (co bylo vytvořeno, varování, duplikáty) a přehled všech složek. Log lze zkopírovat pro archivaci.",
    category: "info",
    tourOrder: 11,
    dataFlow: [
      { targetHelpId: "dochub-structure", label: "Vytváří složky podle definované struktury" },
    ],
  },
  {
    id: "dochub-history",
    view: "project",
    tab: "documents",
    label: "Historie běhů",
    description: "Rozbalitelný seznam všech předchozích synchronizací — stav, počet akcí, varování a chyby.",
    detail: "Filtry: 'Jen chyby' zobrazí jen neúspěšné běhy, 'Akce > 0' jen běhy s vytvořenými složkami, výběr období (1-90 dnů). U každého běhu vidíte stav (Dokončeno/Chyba/Běží), počet akcí a tlačítka pro zobrazení logu nebo přehledu složek. Staré záznamy (>20 dnů) lze hromadně smazat.",
    category: "info",
    tourOrder: 12,
  },

  {
    id: "documents-pricelists",
    view: "project",
    tab: "documents",
    label: "Ceníky",
    description: "Odkaz na ceníky a rozpočtové podklady projektu.",
    detail: "Zadejte odkaz na umístění ceníků (URL nebo cesta). Pokud je napojen Složkomat, zobrazí se i rychlý odkaz na složku ceníků v projektové struktuře.",
    category: "data-entry",
    tourOrder: 13,
  },

  // === CONTRACTS TAB ===
  {
    id: "contracts-subtabs",
    view: "project",
    tab: "contracts",
    label: "Sekce smluv",
    description: "Přepínání mezi: Přehled (souhrn), Smlouvy (seznam), Dodatky a Čerpání.",
    category: "navigation",
    tourOrder: 1,
  },
  {
    id: "contracts-overview",
    view: "project",
    tab: "contracts",
    label: "Přehled smluv",
    description: "Souhrnný pohled na smluvní portfolio projektu — celkový objem, počet smluv, stav čerpání.",
    category: "info",
    tourOrder: 2,
    dataFlow: [
      { targetHelpId: "overview-internal-budget", label: "Zasmluvněná částka v přehledu projektu" },
    ],
  },
  {
    id: "contracts-list",
    view: "project",
    tab: "contracts",
    label: "Seznam smluv",
    description: "Tabulka nebo přehled všech smluv projektu s detaily — dodavatel, předmět, částka, stav.",
    detail: "Dvě zobrazení: Tabulka (kompaktní řádky) a Přehled smluv (rozšířené karty). Každá smlouva je napojena na poptávkovou kategorii a subdodavatele z Pipeline.",
    category: "info",
    tourOrder: 3,
  },
  {
    id: "contracts-amendments",
    view: "project",
    tab: "contracts",
    label: "Dodatky ke smlouvám",
    description: "Správa dodatků — změny ceny, termínů nebo rozsahu jednotlivých smluv.",
    detail: "Každý dodatek navyšuje nebo snižuje původní cenu smlouvy. Součet dodatků se promítá do celkové zasmluvněné částky projektu.",
    category: "data-entry",
    tourOrder: 4,
    dataFlow: [
      { targetHelpId: "overview-investor-finances", label: "Změny se promítají do financí" },
    ],
  },
  {
    id: "contracts-drawdowns",
    view: "project",
    tab: "contracts",
    label: "Čerpání",
    description: "Sledování finančního čerpání smluv — kolik z celkové částky bylo již fakturováno a uhrazeno.",
    category: "info",
    tourOrder: 5,
  },
];
