import type { HelpEntry } from "../types";

export const projectOverviewHelp: HelpEntry[] = [
  {
    id: "overview-scope-toggle",
    view: "project-overview",
    label: "Rozsah analýzy",
    description: "Přepínání mezi analýzou celé organizace a konkrétního projektu.",
    detail: "Režim 'Organizace' zobrazuje souhrnné statistiky přes všechny projekty. Režim 'Projekt' filtruje data na vybranou stavbu.",
    category: "navigation",
    tourOrder: 1,
  },
  {
    id: "overview-project-filter",
    view: "project-overview",
    label: "Výběr projektu",
    description: "Filtrování analytiky na konkrétní projekt. Dostupné pouze v režimu 'Projekt'.",
    category: "navigation",
    tourOrder: 2,
  },
  {
    id: "overview-kpi",
    view: "project-overview",
    label: "Souhrnné metriky",
    description: "Čtyři klíčové ukazatele: Objem zakázek, Počet poptávek, Počet dodavatelů a Počet nabídek.",
    detail: "Metriky se počítají ze všech projektů (nebo vybraného projektu). Objem zakázek = součet cen vítězných nabídek. Ostatní metriky počítají celkové množství záznamů v systému.",
    category: "info",
    tourOrder: 3,
  },
  {
    id: "overview-supplier-analysis",
    view: "project-overview",
    label: "Analýza dodavatelů",
    description: "Podrobná analýza subdodavatelů — kolikrát vyhráli, objemy zakázek, úspěšnost nabídek.",
    detail: "Kliknutím na dodavatele zobrazíte detail: všechny jeho nabídky, celkový zasmluvněný objem, realizaci SOD, úspěšnost a průměrnou odchylku cen od rozpočtu.",
    category: "info",
    tourOrder: 4,
  },
  {
    id: "overview-charts",
    view: "project-overview",
    label: "Grafy a vizualizace",
    description: "Sloupcové grafy top dodavatelů, koláčový graf stavů nabídek a ukazatel odchylky rozpočtu.",
    detail: "Graf SOD Počet = kolikrát dodavatel vyhrál. Graf Objemy = finanční objem zakázek dodavatele. Koláč = distribuce stavů nabídek (nabídka/shortlist/SOD/odmítnuto). Ukazatel = jak moc se nabídky odchylují od plánovaného rozpočtu.",
    category: "info",
    tourOrder: 5,
  },
  {
    id: "overview-trends",
    view: "project-overview",
    label: "Trendy",
    description: "Historické trendy — vývoj objemu zakázek a aktivity nabídek v čase (po měsících a letech).",
    category: "info",
    tourOrder: 6,
  },
  {
    id: "overview-export-pdf",
    view: "project-overview",
    label: "Export do PDF",
    description: "Exportuje analýzu dodavatelů do PDF dokumentu pro sdílení a reporting.",
    category: "action",
    tourOrder: 7,
  },
];
