import type { HelpEntry } from "../types";

export const settingsHelp: HelpEntry[] = [
  {
    id: "settings-main-tabs",
    view: "settings",
    label: "Hlavní záložky",
    description: "Přepínání mezi Uživatelskými nastaveními, Organizací a Administrací (pro adminy).",
    detail: "Uživatel = osobní nastavení (profil, notifikace, nástroje). Organizace = nastavení organizace. Admin = správa uživatelů, předplatných, AI a compliance (dostupné pouze administrátorům).",
    category: "navigation",
    tourOrder: 1,
  },
  {
    id: "settings-profile",
    view: "settings",
    label: "Profil a vzhled",
    description: "Nastavení profilu, motivu aplikace (světlý/tmavý) a jazykových preferencí.",
    category: "data-entry",
    tourOrder: 2,
  },
  {
    id: "settings-subscription",
    view: "settings",
    label: "Předplatné",
    description: "Zobrazení aktuálního tarifu, fakturačních údajů a možnost upgradu na vyšší plán.",
    detail: "Tarify: Free, Starter, Pro, Enterprise. Vyšší tarify odemykají pokročilé funkce jako Pipeline, Harmonogram, DocHub a AI asistenta.",
    category: "info",
    tourOrder: 3,
  },
  {
    id: "settings-notifications",
    view: "settings",
    label: "Notifikace",
    description: "Nastavení upozornění — e-mailové notifikace, push notifikace a jejich frekvence.",
    category: "data-entry",
    tourOrder: 4,
  },
  {
    id: "settings-backup",
    view: "settings",
    label: "Zálohování dat",
    description: "Záloha a obnovení dat projektu. Vytvoření zálohy exportem dat, obnovení z dříve uloženého souboru.",
    detail: "Záloha obsahuje všechny projekty, kontakty, nabídky a nastavení. Formát JSON. Doporučujeme pravidelné zálohy před většími změnami.",
    category: "action",
    tourOrder: 5,
  },
  {
    id: "settings-contacts-import",
    view: "settings",
    label: "Import kontaktů",
    description: "Hromadný import subdodavatelů z Excel nebo CSV souboru. Průvodce krok za krokem.",
    detail: "Průvodce vás provede: výběr souboru → mapování sloupců → kontrola dat → import. Podporuje .xlsx a .csv. Duplicity se detekují podle názvu firmy.",
    category: "action",
    tourOrder: 6,
    dataFlow: [
      { targetHelpId: "contacts-list", label: "Importované kontakty se objeví v Kontaktech" },
    ],
  },
  {
    id: "settings-excel-tools",
    view: "settings",
    label: "Excel nástroje",
    description: "Sada nástrojů pro práci s Excel soubory — Unlocker (odemknutí), Merger (sloučení) a Indexer.",
    detail: "Excel Unlocker: odemkne chráněné listy a sešity. Excel Merger: sloučí více Excel souborů do jednoho. Excel Indexer: vytvoří index obsahu z více souborů. Nástroje běží lokálně (desktop) nebo přes server.",
    category: "info",
    tourOrder: 7,
  },
  {
    id: "settings-contacts-export",
    view: "settings",
    label: "Export kontaktů",
    description: "Stažení seznamu subdodavatelů jako Excel (.xlsx) nebo CSV soubor.",
    category: "action",
    tourOrder: 8,
  },
  {
    id: "settings-admin-users",
    view: "settings",
    label: "Správa uživatelů",
    description: "Administrátorský panel pro správu uživatelů organizace — role, oprávnění, blokování účtů.",
    detail: "Dostupné pouze pro administrátory. Umožňuje měnit role (admin/user), spravovat předplatná a monitorovat aktivitu uživatelů.",
    category: "action",
    tourOrder: 9,
  },
  {
    id: "settings-admin-ai",
    view: "settings",
    label: "Nastavení AI",
    description: "Konfigurace AI asistenta (Viki) — model, kontext, oprávnění a limity.",
    category: "data-entry",
    tourOrder: 10,
  },
];
