import React, { Suspense, lazy } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { contacts, contract, project, projects, task, user } from './fixtureData';
import { DEFAULT_STATUSES } from '@/config/constants';
import '@/index.css';
import './preview.css';

const noop = () => {};
const blocked = async () => { throw new Error('Ukázka neukládá ani neodesílá data.'); };
const screen = new URLSearchParams(location.search).get('screen') || 'prehled';
const screens: Record<string, () => Promise<{ default: React.ComponentType }>> = {
  'nabidka-uprava': async () => { const {EditBidModal:C}=await import('@features/projects/pipeline/ui/EditBidModal');return {default:()=> <C bid={{...project.bids!.elektro[0],selectionRound:2,priceHistory:{1:'1 450 000 Kč',2:'1 380 000 Kč'}}} subcontractor={contacts[0]} statuses={DEFAULT_STATUSES} onClose={noop} onSave={noop}/>}; },
  'vr-tabulka': async () => { const {PipelineOverview:C}=await import('@features/projects/pipeline/ui/PipelineOverview');return {default:()=> <C currentUserId={user.id} categories={project.categories} bids={project.bids!} contracts={[contract]} searchQuery="" demandFilter="all" viewMode="table" onFilterChange={noop} onViewModeChange={noop} onCategoryClick={noop} onAddClick={noop} onEditCategory={noop} onDeleteCategory={noop} onToggleCategoryComplete={noop} exportMeta={{organizationName:"Javor — ukázka",projectTitle:project.title,projectStatus:"realization",exportedBy:user.name,appVersion:"1.9.36"}} onExportError={noop}/>}; },
  objednatel: async () => { const {InvestorBillingPage:C}=await import('@features/projects/contracts/investor/InvestorBillingPage');return {default:()=> <C projectDetails={project} onUpdateDetails={noop}/>}; },
  'sablona-editor': async () => { const {TemplateManager:C}=await import('@features/projects/documents/ui/TemplateManager');return {default:()=> <C project={project} initialTemplateId="manual-inquiry" onClose={noop} onSelectTemplate={noop}/>}; },
  'prehled-smluv': async () => { const {ContractOverview:C}=await import('@features/contracts-overview/ContractOverview');return {default:C}; },
  'smlouva-dokument': async () => { const {OcrDocumentSection:C}=await import('@features/projects/contracts/workspace/sections/OcrDocumentSection');return {default:()=> <C contract={contract} onRefresh={noop}/>}; },
  ukoly: async () => { const {TasksPage:C}=await import('@features/tasks/ui/TasksPage');return {default:()=> <div style={{height:820}}><C skin="industrial"/></div>}; },
  mapa: async () => { const {ProjectMapView:C}=await import('@features/maps/components/ProjectMapView');return {default:()=> <div style={{height:720,position:'relative'}}><C projectId={project.id!} projectDetails={{...project,latitude:49.195,longitude:16.607}} contacts={contacts.map((c,i)=>({...c,latitude:49.20+i*.015,longitude:16.62+i*.02}))} statuses={DEFAULT_STATUSES}/></div>}; },
  biometrie: async () => { const {BiometricSettings:C}=await import('@features/settings/BiometricSettings');return {default:C}; },
  stavby: async () => { const {ProjectManager:C}=await import('@features/projects/ProjectManager'); return {default:()=> <div style={{height:750}}><C projects={projects} onAddProject={blocked} onDeleteProject={noop} onCloneTenderToRealization={blocked} onArchiveProject={noop} skin="industrial"/></div>}; },
  portfolio: async () => { const {ProjectOverview:C}=await import('@features/projects/ProjectOverview'); return {default:()=> <C projects={projects} projectDetails={{[project.id!]:project}} user={user} skin="industrial"/>}; },
  tym: async () => { const {ProjectTeamSettings:C}=await import('@features/projects/team/ProjectTeamSettings'); return {default:()=> <C projectId={project.id!} organizationId={user.organizationId} currentUserId={user.id}/>}; },
  'import-kontaktu': async () => { const {ContactsImportWizard:C}=await import('@shared/ui/ContactsImportWizard'); return {default:()=> <C contacts={contacts} statuses={DEFAULT_STATUSES} onImportContacts={blocked}/>}; },
  'excel-odemceni': async () => { const {ExcelUnlockerProSettings:C}=await import('@features/settings/ExcelUnlockerProSettings'); return {default:C}; },
  'excel-spojeni': async () => { const {ExcelMergerProSettings:C}=await import('@features/settings/ExcelMergerProSettings'); return {default:C}; },
  'excel-indexace': async () => { const {ExcelIndexerSettings:C}=await import('@features/settings/ExcelIndexerSettings'); return {default:C}; },
  prihlaseni: async () => { const {LoginPage:C}=await import('@features/auth/ui/LoginPage'); return {default:C}; },
  slozkomat: async () => { const {DocHubStructureEditor:C}=await import('@features/projects/documents/ui/dochub/DocHubStructureEditor'); const {DocHubStatusCard:S}=await import('@features/projects/documents/ui/dochub/DocHubStatusCard'); const {DOC_HUB_STRUCTURE_V1,DEFAULT_DOCHUB_HIERARCHY}=await import('@shared/dochub/docHub'); const state={provider:'onedrive',mode:'user',rootName:'Javor — ukázková složka',rootLink:'/Ukazky/Javor',onlineRootLink:'',isSharedProject:false,hasPersonalLocalRoot:true,isEditingStructure:true,structureDraft:DOC_HUB_STRUCTURE_V1,extraTopLevelDraft:[],extraSupplierDraft:[],hierarchyDraft:DEFAULT_DOCHUB_HIERARCHY,isAutoCreating:false,isConnected:true,autoCreateProgress:null} as unknown as React.ComponentProps<typeof C>['state']; const actions={} as React.ComponentProps<typeof C>['actions'];const setters={} as React.ComponentProps<typeof C>['setters'];return {default:()=> <><S state={state} actions={actions} setters={setters} showModal={noop}/><C state={state} actions={actions} setters={setters} showModal={noop}/></>}; },
  prehled: async () => { const { ProjectOverviewNew: C } = await import('@features/projects/ui/ProjectOverviewNew'); return { default: () => <C project={project} onUpdate={noop} skin="industrial" /> }; },
  kontakty: async () => { const { SubcontractorCardsView: C } = await import('@features/contacts/ui/SubcontractorCardsView'); return { default: () => <C contacts={contacts} statuses={DEFAULT_STATUSES} selectedIds={new Set(['javor'])} onSelectionChange={noop} onEditContact={noop} /> }; },
  'kontakt-formular': async () => { const { CreateContactModal: C } = await import('@features/projects/pipeline/ui/CreateContactModal'); return { default: () => <C initialName={contacts[0].company} initialData={contacts[0]} existingSpecializations={['Elektroinstalace', 'Slaboproud']} statuses={DEFAULT_STATUSES} onClose={noop} onSave={noop} /> }; },
  'vr-formular': async () => { const { CategoryFormModal: C } = await import('@features/projects/pipeline/ui/CategoryFormModal'); return { default: () => <C isOpen mode="edit" initialData={project.categories[0]} onClose={noop} onSubmit={blocked} /> }; },
  'hromadny-email': async () => { const { PipelineBulkEmailConfirmationModal: C } = await import('@features/projects/ui/PipelineBulkEmailConfirmationModal'); const bids = project.bids!.elektro; return { default: () => <C isOpen kind="inquiry" userEmail={user.email} selection={{candidateBids:bids,recipientBids:bids,emails:bids.map(b=>b.email!),missingEmailBids:[],invalidEmailBids:[]}} isSubmitting={false} onConfirm={blocked} onCancel={noop} /> }; },
  harmonogram: async () => { const { ProjectSchedule: C } = await import('@features/projects/ui/ProjectSchedule'); return { default: () => <div style={{height:620,display:'flex'}}><C projectId={project.id!} projectTitle={project.title} categories={project.categories} /></div> }; },
  dokumenty: async () => { const { DocsLinkSection: C } = await import('@features/projects/documents/ui/DocsLinkSection'); return { default: () => <C project={project} hasDocsLink isEditing={false} onEditToggle={noop} linkValue="" onLinkValueChange={noop} onSave={noop} showModal={noop} onUpdate={noop} /> }; },
  sablony: async () => { const { TemplatesSection: C } = await import('@features/projects/documents/ui/TemplatesSection'); return { default: () => <C project={project} templateName="Poptávka Javor" materialTemplateName="Materiál Javor" losersTemplateName="Poděkování Javor" openTemplateManager={noop} /> }; },
  ceniky: async () => { const { PriceListsSection: C } = await import('@features/projects/documents/ui/PriceListsSection'); return { default: () => <C project={{...project,priceListLink:'https://example.com/javor/ceniky'}} isEditing={false} onEditToggle={noop} linkValue="" onLinkValueChange={noop} onSave={noop} isDocHubConnected={false} docHubCenikyLink={null} showModal={noop} /> }; },
  'smlouva-finance': async () => { const {FinancialSection:F}=await import('@features/projects/contracts/workspace/sections/FinancialSection'); const {DrawdownsSection:D}=await import('@features/projects/contracts/workspace/sections/DrawdownsSection'); return {default:()=> <><F contract={contract}/><D contract={contract}/></>}; },
  'smlouva-faktury': async () => { const {InvoicesSection:C}=await import('@features/projects/contracts/workspace/sections/InvoicesSection'); return {default:()=> <C contract={contract} onRefresh={noop}/>}; },
  'smlouva-pozastavky': async () => { const {RetentionSection:R}=await import('@features/projects/contracts/workspace/sections/RetentionSection'); const {WarrantySection:W}=await import('@features/projects/contracts/workspace/sections/WarrantySection'); return {default:()=> <><R contract={contract} onRefresh={noop}/><W contract={contract}/></>}; },
  'smlouva-dodatky': async () => { const {AmendmentsSection:C}=await import('@features/projects/contracts/workspace/sections/AmendmentsSection'); return {default:()=> <C contract={contract} onRefresh={noop}/>}; },
  'smlouva-formular': async () => { const {ContractEditDialog:C}=await import('@features/projects/contracts/forms/ContractEditDialog'); return {default:()=> <C projectId={project.id!} contract={contract} onClose={noop} onSaved={noop}/>}; },
  ukol: async () => { const {TaskDetail:C}=await import('@features/tasks/ui/TaskDetail'); return {default:()=> <C item={{task,subtasks:[{...task,id:'task-2',title:'Ověřit zahrnutí revizí',parentTaskId:task.id,priority:3}]}} selectedTask={task} todoProjects={[]} onSelectTask={noop} onDeleted={noop}/>}; },
  upozorneni: async () => { const {NotificationSettings:C}=await import('@features/settings/NotificationSettings'); return {default:C}; },
  zabezpeceni: async () => { const {UserSecuritySettings:C}=await import('@features/settings/UserSecuritySettings'); return {default:C}; },
  'ai-pristupy': async () => { const {McpAccessSettings:C}=await import('@features/settings/McpAccessSettings'); return {default:C}; },
  microsoft: async () => { const {MicrosoftAccountSettings:C}=await import('@features/settings/MicrosoftAccountSettings'); return {default:C}; },
  zalohy: async () => { const {BackupSettings:C}=await import('@features/backup/ui/BackupSettings'); return {default:C}; },
  profil: async () => { const {ProfileSettings:C}=await import('@features/settings/ProfileSettings'); return {default:()=> <C theme="dark" skin="industrial" primaryColor="#a4c5ad" onSetTheme={noop} onSetSkin={noop} onSetPrimaryColor={noop} contactStatuses={DEFAULT_STATUSES} onUpdateStatuses={noop} onDeleteContacts={noop} contacts={contacts} user={user}/>}; },
};
const Component = lazy(screens[screen] || screens.prehled);
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={new QueryClient()}><main className="manual-fixtures catalog-fixtures tf-app-main"><section className="shot" id="catalog-shot"><div className="fixture-caption">TENDER FLOW / UŽIVATELSKÝ POSTUP<span>Syntetická ukázka · bez ukládání a odesílání</span></div><Suspense fallback={<p>Načítání ukázky…</p>}><Component/></Suspense></section></main></QueryClientProvider>);
